### ISSUE TITLE
master节点和agent节点之间的疑问

### ISSUE THREAD

**Issue by yaobo-lab** [dalonghahaha/Asgard#2]
master节点和agent节点之间通过grpc协议交换数据。那么GRPC 通信有校验吗 ？例如令牌

**Comment by dalonghahaha** [comment]
目前的设计没有涉及校验，后续可考虑添加支持

**Comment by yaobo-lab** [comment]
> 目前的设计没有涉及校验，后续可考虑添加支持

没有校验那就坑了。跨机房问题

**Comment by dalonghahaha** [comment]
> > 目前的设计没有涉及校验，后续可考虑添加支持
> 
> 没有校验那就坑了。跨机房问题

好的，谢谢建议，后续的迭代会考虑这个问题

**Comment by yaobo-lab** [comment]
> > > 目前的设计没有涉及校验，后续可考虑添加支持
> > 
> > 
> > 没有校验那就坑了。跨机房问题
> 
> 好的，谢谢建议，后续的迭代会考虑这个问题

期待
